import assert from "node:assert/strict";
import { blankProject, blankTrack, blankClip, noteEvents, regionHashes } from "./store.js";
import { mixerFutureSeconds, mixerReach, mixerSigBundle } from "./mixer.js";
const limiter = (id) => ({ id, type: "limiter", enabled: true, params: { lookahead_ms: 10 } });
const doc = blankProject("future-context", { bpm: 120, lengthBars: 8 });
const t = blankTrack("Future transient", "pluck");
t.inserts = [limiter("one"), limiter("two")];
const c = blankClip(1, 8, {});
c.notes.push({ id: "future-note", bar: 5, beat: 1, tick: 64, durTicks: 480, pitch: 60, vel: 100, by: "agent" });
t.clips.push(c); doc.tracks.push(t); doc.master.inserts = [limiter("three")];
assert.ok(Math.abs(mixerFutureSeconds(doc) - 0.066) < 1e-9);
assert.ok(mixerReach(doc, t).back > 0.033);
assert.ok(noteEvents(doc)[0].reach0 < 8, "A transient after the boundary reaches the previous region");
const before = regionHashes(doc);
c.notes[0].pitch = 62;
assert.notEqual(regionHashes(doc)[0], before[0], "Editing future input invalidates the preceding audio");
assert.ok(mixerSigBundle(doc).master.includes("future-context:1"));
for (const i of [...t.inserts, ...doc.master.inserts]) i.enabled = false;
assert.equal(mixerFutureSeconds(doc), 0);
console.log("6 future-context dependency checks passed");
