"""Build web/style-tags.js from "Genre List.txt" (the Music page's style chips).

Usage, from the Studio folder:
    python scripts/build-style-tags.py "Genre List.txt" .
"""
import json
import re
import sys

src, root = sys.argv[1], sys.argv[2].rstrip("/\\") + "/"

# The list arrives with punctuation stripped ("rb", "singersongwriter", "postpunk").
# Put back the spellings a music model has actually read, word by word.
WORD_FIX = {
    "rb": "r&b", "singersongwriter": "singer-songwriter", "lofi": "lo-fi",
    "hiphop": "hip hop", "kpop": "k-pop", "jpop": "j-pop", "cpop": "c-pop",
    "dnb": "drum and bass", "auteurcompositeurinterprete": "auteur-compositeur-interprete",
}
POST = re.compile(r"^post(punk|rock|grunge|metal|hardcore|teen|bop|disco|minimalism|romantic|romanticism|industrial|doom|black)$")


def fix(genre):
    out = []
    for w in genre.split():
        w = WORD_FIX.get(w, w)
        m = POST.match(w)
        out.append(f"post-{m.group(1)}" if m else w)
    return " ".join(out)


seen, genres = set(), []
for line in open(src, encoding="utf8"):
    g = fix(line.strip().lower())
    if g and g not in seen:
        seen.add(g)
        genres.append(g)

# Everything else a style line is made of. Written for YuE2's one-line tags and
# MiniMax's caption alike: plain words a music model has seen in its captions.
VOCALS = [
    "female vocal", "male vocal", "female lead vocal", "male lead vocal", "duet, male and female",
    "breathy female vocal", "raspy male vocal", "soulful female vocal", "deep baritone male vocal",
    "high tenor male vocal", "operatic soprano", "falsetto", "whispered vocals", "intimate close-mic vocal",
    "powerful belting vocal", "harmonized backing vocals", "gang vocals", "call and response vocals",
    "gospel choir", "choir", "children's choir", "a cappella", "rap verses", "fast rap flow",
    "melodic rap", "spoken word", "auto-tuned vocals", "vocoder vocals", "growled vocals",
    "screamed vocals", "clean and harsh vocals", "yodeling", "scat singing", "chant vocals",
    "instrumental, no vocals",
]
MOODS = [
    "uplifting", "melancholic", "dark", "dreamy", "energetic", "aggressive", "romantic", "nostalgic",
    "euphoric", "haunting", "chill", "epic", "playful", "bittersweet", "anthemic", "intimate",
    "mysterious", "triumphant", "somber", "groovy", "hopeful", "angry", "sensual", "peaceful",
    "tense", "whimsical", "cinematic", "heartfelt", "rebellious", "hypnotic",
]
INSTRUMENTS = [
    "acoustic guitar", "fingerpicked guitar", "electric guitar", "distorted guitars", "jangly guitars",
    "piano", "rhodes piano", "hammond organ", "synth pads", "analog synth lead", "arpeggiated synths",
    "analog synth bass", "808 bass", "upright bass", "slap bass", "strings", "string quartet",
    "full orchestra", "brass section", "saxophone", "trumpet", "violin", "cello", "flute", "harp",
    "banjo", "mandolin", "pedal steel", "sitar", "koto", "marimba", "steel drums", "accordion",
    "bagpipes", "live drums", "brushed drums", "drum machine", "breakbeats", "trap hi-hats",
    "hand percussion", "tabla", "congas", "handclaps", "vinyl crackle",
]
RHYTHM = [
    "slow tempo", "mid-tempo", "fast tempo", "70 BPM", "85 BPM", "92 BPM", "100 BPM", "110 BPM",
    "120 BPM", "128 BPM", "140 BPM", "150 BPM", "174 BPM", "half-time feel", "four-on-the-floor",
    "swing rhythm", "shuffle groove", "6/8 feel", "3/4 waltz time", "syncopated groove", "driving beat",
    "laid-back groove", "double-time drums",
]
PRODUCTION = [
    "major key", "minor key", "key change", "big anthemic chorus", "catchy hook", "build and drop",
    "slow build", "fade-out ending", "lo-fi warmth", "warm tape saturation", "polished modern mix",
    "raw live recording", "bedroom production", "wide stereo", "reverb-drenched", "dry and punchy",
    "heavy sidechain", "crisp highs", "sub-heavy low end", "vintage 70s sound", "80s production",
    "90s production", "stripped-back arrangement", "wall of sound", "cinematic swells",
]

body = f"""/* Style tags for the Music page's chip row (paintChips in app.js).
 *
 * GENRES is the list in "Genre List.txt" (6,000+ genres), with duplicates
 * dropped and its stripped punctuation put back ("rb" -> "r&b",
 * "singersongwriter" -> "singer-songwriter", "postpunk" -> "post-punk") so the
 * model reads real words. The other lists are the rest of a style line: who
 * sings, the mood, the instruments, the tempo and the production. The row
 * shows a random handful of each, and the random button deals a new hand.
 * Generated by scripts/build-style-tags.py from the genre list; edit that list
 * (or the script, for the other lists), not this file. */
export const GENRES = {json.dumps(genres, ensure_ascii=False)};
export const VOCALS = {json.dumps(VOCALS, ensure_ascii=False)};
export const MOODS = {json.dumps(MOODS, ensure_ascii=False)};
export const INSTRUMENTS = {json.dumps(INSTRUMENTS, ensure_ascii=False)};
export const RHYTHM = {json.dumps(RHYTHM, ensure_ascii=False)};
export const PRODUCTION = {json.dumps(PRODUCTION, ensure_ascii=False)};

/* How many of each the row shows. Genres lead: they are what the list is for. */
export const HAND = Object.freeze({{ GENRES: 10, VOCALS: 3, MOODS: 2, INSTRUMENTS: 3, RHYTHM: 1, PRODUCTION: 2 }});
const POOLS = {{ GENRES, VOCALS, MOODS, INSTRUMENTS, RHYTHM, PRODUCTION }};

/** Pure: a random hand of style tags, no repeats. `rand` is injectable for tests. */
export function dealStyleTags(rand = Math.random, hand = HAND) {{
  const out = [];
  for (const [pool, n] of Object.entries(hand)) {{
    // A partial Fisher-Yates shuffle: exactly n steps whatever `rand` returns, never a retry loop.
    const list = POOLS[pool].slice(), take = Math.min(n, list.length);
    for (let i = 0; i < take; i++) {{
      const j = i + Math.min(list.length - i - 1, Math.floor(Math.max(0, rand()) * (list.length - i)));
      [list[i], list[j]] = [list[j], list[i]];
      if (!out.includes(list[i])) out.push(list[i]);
    }}
  }}
  return out;
}}
"""
open(root + "web/style-tags.js", "w", encoding="utf8", newline="\n").write(body)
print("genres", len(genres), "->", root + "web/style-tags.js")
